// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/register": {
            "post": {
                "description": "Accepts an email address and sends a one-time login link valid for 15 minutes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register / Request Magic Link",
                "parameters": [
                    {
                        "description": "JSON body with email field",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Confirmation that the email was sent",
                        "schema": {
                            "$ref": "#/definitions/api.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid email",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to store token or send email",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/session/consume-code": {
            "post": {
                "description": "Redeems a valid 6-digit delegation code to provision a new child session node in the Neo4j provenance graph. Requested scopes must be limited to read and fertile and be a subset of the parent session scopes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session Delegation"
                ],
                "summary": "Consume Session Invitation Code",
                "parameters": [
                    {
                        "description": "JSON body containing the 6-digit code, device name, and requested scopes",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ConsumeDelegationCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns a brand new persistent session token and active scopes",
                        "schema": {
                            "$ref": "#/definitions/api.ConsumeDelegationCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or requested scopes are not allowed",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The code has expired, been used, or is mathematically invalid",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Parent session was revoked, inactive, lacks fertile scope, or requested scopes exceed parent scopes",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/session/generate-code": {
            "post": {
                "description": "Generates a temporary, single-use 6-digit code or URL link from an active, fertile session to invite a new device. Requested scopes are chosen when the code is consumed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session Delegation"
                ],
                "summary": "Generate Session Invitation Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003ctoken\u003e where token is a Session.token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the 6-digit code, direct link, and TTL expiry",
                        "schema": {
                            "$ref": "#/definitions/api.GenerateDelegationCodeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized due to missing, invalid, or inactive session",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Parent session lacks the fertile scope required to delegate",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal failure generating crypto code or saving to cache",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/verify": {
            "post": {
                "description": "Consumes a one-time token from the magic link and returns a session token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify Magic Link Token",
                "parameters": [
                    {
                        "description": "JSON body with token, name, and scopes fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.VerifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session token and email",
                        "schema": {
                            "$ref": "#/definitions/api.VerifyResponse"
                        }
                    },
                    "400": {
                        "description": "Missing token or invalid scopes",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token expired or invalid",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create session",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/clients": {
            "post": {
                "description": "Creates a new OAuth client owned by the authenticated account. Requires the clients scope.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clients"
                ],
                "summary": "Create OAuth Client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003ctoken\u003e where token is a Session.token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Client name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateClientRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the generated client credentials",
                        "schema": {
                            "$ref": "#/definitions/api.CreateClientResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid client name",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized due to missing or invalid session",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Session lacks the clients scope",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create client in the graph",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Returns the health status of the API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/oauth/authorize": {
            "post": {
                "description": "Creates a short-lived authorization code for the authenticated user and returns the client redirect URL. Requires a valid session with the clients scope excluded from granted OAuth scopes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2 SSO"
                ],
                "summary": "Authorize SSO Request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003ctoken\u003e where token is a Session.token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "OAuth2 client and redirect parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AuthorizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the callback URL containing the auth code",
                        "schema": {
                            "$ref": "#/definitions/api.AuthorizeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or unknown client",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized due to missing or invalid session",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Requested scope exceeds session scopes",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to store authorization code",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/oauth/token": {
            "post": {
                "description": "Consumes a short-lived authorization code and issues a signed JWT access token with a Redis-backed jti nonce for revocation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2 SSO"
                ],
                "summary": "Exchange Auth Code for JWT",
                "parameters": [
                    {
                        "description": "JSON body containing grant_type, code, client_id, and client_secret",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TokenExchangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the standard OAuth2 JWT access token payload",
                        "schema": {
                            "$ref": "#/definitions/api.TokenExchangeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or unsupported grant type",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid client credentials or authorization code",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to mint access token",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AuthorizeRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "redirect_uri": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "api.AuthorizeResponse": {
            "type": "object",
            "properties": {
                "redirect_to": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "api.ConsumeDelegationCodeRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "device_name": {
                    "type": "string"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.ConsumeDelegationCodeResponse": {
            "type": "object",
            "properties": {
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "session_token": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "authenticated"
                }
            }
        },
        "api.CreateClientRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "api.CreateClientResponse": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid_request"
                }
            }
        },
        "api.GenerateDelegationCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "api.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "api.RegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Check your email for a verification link."
                }
            }
        },
        "api.TokenExchangeRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "grant_type": {
                    "type": "string"
                },
                "redirect_uri": {
                    "type": "string"
                }
            }
        },
        "api.TokenExchangeResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "api.VerifyRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "api.VerifyResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "sessionToken": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Graph Auth",
	Description:      "This is the core REST API for Graph Auth.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
