// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/register": {
            "post": {
                "description": "Accepts an email address and sends a one-time login link valid for 15 minutes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register / Request Magic Link",
                "parameters": [
                    {
                        "description": "JSON body with email field",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Confirmation that the email was sent",
                        "schema": {
                            "$ref": "#/definitions/api.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid email",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to store token or send email",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/session/consume-code": {
            "post": {
                "description": "Redeems a valid 6-digit delegation code to provision a new child session node in the Neo4j provenance graph. Requested scopes must be limited to read and fertile and be a subset of the parent session scopes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session Delegation"
                ],
                "summary": "Consume Session Invitation Code",
                "parameters": [
                    {
                        "description": "JSON body containing the 6-digit code, device name, and requested scopes",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ConsumeDelegationCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns a brand new persistent session token and active scopes",
                        "schema": {
                            "$ref": "#/definitions/api.ConsumeDelegationCodeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or requested scopes are not allowed",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "The code has expired, been used, or is mathematically invalid",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Parent session was revoked, inactive, lacks fertile scope, or requested scopes exceed parent scopes",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/session/generate-code": {
            "post": {
                "description": "Generates a temporary, single-use 6-digit code or URL link from an active, fertile session to invite a new device. Requested scopes are chosen when the code is consumed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session Delegation"
                ],
                "summary": "Generate Session Invitation Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003ctoken\u003e where token is a Session.token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the 6-digit code, direct link, and TTL expiry",
                        "schema": {
                            "$ref": "#/definitions/api.GenerateDelegationCodeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized due to missing, invalid, or inactive session",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Parent session lacks the fertile scope required to delegate",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal failure generating crypto code or saving to cache",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/session/invalidate": {
            "post": {
                "description": "Permanently deactivates the authenticated session and every descendant it has spawned. Used on logout — cannot be undone.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session Delegation"
                ],
                "summary": "Invalidate Session Tree",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003ctoken\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session and all descendants invalidated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing or invalid session",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/verify": {
            "post": {
                "description": "Consumes a one-time token from the magic link and returns a session token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify Magic Link Token",
                "parameters": [
                    {
                        "description": "JSON body with token, name, and scopes fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.VerifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Session token and email",
                        "schema": {
                            "$ref": "#/definitions/api.VerifyResponse"
                        }
                    },
                    "400": {
                        "description": "Missing token or invalid scopes",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Token expired or invalid",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create session",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Returns the health status of the API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/nodes/me": {
            "get": {
                "description": "Returns the session node associated with the authenticated Bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nodes"
                ],
                "summary": "Get Current Node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003ctoken\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Current session node",
                        "schema": {
                            "$ref": "#/definitions/api.NodeResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid session",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Node not found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/nodes/tree": {
            "get": {
                "description": "Returns every session node in the account tree that the authenticated token belongs to.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nodes"
                ],
                "summary": "Get Session Tree",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003ctoken\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "All nodes in the account tree",
                        "schema": {
                            "$ref": "#/definitions/api.NodeTreeResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid session",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Lookup failed",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/nodes/{id}/invalidate": {
            "post": {
                "description": "Permanently deactivates the target session and every session it has spawned. The target must be in the caller's account tree.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Nodes"
                ],
                "summary": "Invalidate Node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003ctoken\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session token of the node to invalidate",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Node invalidated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing or invalid session",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Target not in caller's tree",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Invalidation failed",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/oauth/authorize": {
            "get": {
                "description": "Evaluates device state. Redirects authenticated devices to a consent screen, and unauthenticated devices to the session delegation flow.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2 SSO"
                ],
                "summary": "Authorize SSO Request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth2 Client ID",
                        "name": "client_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth2 Redirect URI",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth2 State string",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Existing Neo4j Session Token",
                        "name": "X-Session-Token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the status and the next frontend URL to redirect to",
                        "schema": {
                            "$ref": "#/definitions/api.AuthorizeResponse"
                        }
                    },
                    "400": {
                        "description": "Missing required OAuth2 parameters",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/oauth/confirm": {
            "post": {
                "description": "Verifies the active session and generates a temporary, high-entropy OAuth2 authorization code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2 SSO"
                ],
                "summary": "Confirm SSO Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active Neo4j Session Token",
                        "name": "X-Session-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "JSON body containing client_id, redirect_uri, and state",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ConfirmLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the callback URL containing the auth code",
                        "schema": {
                            "$ref": "#/definitions/api.ConfirmLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Session invalid or revoked",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/oauth/token": {
            "post": {
                "description": "Consumes a short-lived authorization code and issues a signed JWT access token backed by Redis.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth2 SSO"
                ],
                "summary": "Exchange Auth Code for JWT",
                "parameters": [
                    {
                        "description": "JSON body containing code, client_id, and client_secret",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TokenExchangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns the standard OAuth2 JWT access token payload",
                        "schema": {
                            "$ref": "#/definitions/api.TokenExchangeResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid, expired, or already consumed authorization code",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.APINode": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "isRoot": {
                    "type": "boolean"
                },
                "label": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "predecessorId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.AuthorizeResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "next_url": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "authenticated"
                }
            }
        },
        "api.ConfirmLoginRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "redirect_uri": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "api.ConfirmLoginResponse": {
            "type": "object",
            "properties": {
                "redirect_to": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "api.ConsumeDelegationCodeRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "device_name": {
                    "type": "string"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.ConsumeDelegationCodeResponse": {
            "type": "object",
            "properties": {
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "session_token": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "authenticated"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid_request"
                }
            }
        },
        "api.GenerateDelegationCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "api.NodeResponse": {
            "type": "object",
            "properties": {
                "node": {
                    "$ref": "#/definitions/api.APINode"
                }
            }
        },
        "api.NodeTreeResponse": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.APINode"
                    }
                }
            }
        },
        "api.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "api.RegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Check your email for a verification link."
                }
            }
        },
        "api.TokenExchangeRequest": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                }
            }
        },
        "api.TokenExchangeResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "api.VerifyRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "api.VerifyResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "sessionToken": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Graph Auth",
	Description:      "This is the core REST API for Graph Auth.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
